package cmd

const (
	MsgStart             = "Добро пожаловать в BotMix! Выберите команду:"
	EnterNameTbc         = "Введите название табака:"
	EnterStrengthTbc     = "Введите крепость табака: Light, Medium, Strong"
	EnterFlavorName      = "Введите название вкуса:"
	EnterFlavorType      = "Введите тип вкуса:"
	DeleteTbc            = "Введите название табака для удаления:"
	AddFlavorTbc         = "Введите название табака для добавления вкуса:"
	DeleteFlavorTbc      = "Введите название табака для удаления вкуса:"
	ShowTbcCatalog       = "Введите название табака для отображения каталога:"
	UnknownCommand       = "Неизвестная команда"
	InvalidStrength      = "Ошибка: Неверная крепость. Введите допустимую крепость: Light, Medium, Strong"
	InvalidFlavorType    = "Ошибка: указанного типа вкуса нет. Виды типов вкуса: Sweet, Sour, SourSweet"
	SuccessAddTobacco    = "Табак добавлен успешно!"
	SuccessDeleteTobacco = "Табак успешно удален"
	SuccessAddFlavor     = "Вкус успешно добавлен!"
	SuccessDeleteFlavor  = "Вкус успешно удален"
	TbcAlreadyExists     = "Табак с таким именем уже существует"
	FlavorAlreadyExists  = "Вкус с таким именем уже существует"
	FlavorNotExists      = "Вкус с таким именем не найден"
	TbcNotFound          = "Табак с таким именем не найден"
	SelectStr            = "Выберите крепость: Light, Medium, Strong"
	SelectFlavorType     = "Выберите тип вкуса: Sweet, Sour, SourSweet"
	ChooseTobacco        = "Выберите табак:"
	FlavorsIsEmpty       = "У данного табака нет вкусов"
	ChooseFlavors        = "Выберите вкус:"
)
